### ISSUE TITLE
Extra entry in race list

### ISSUE THREAD

**Issue by tvesalainen** [tvesalainen/hoski-weblib#1]
Entry 
Stickan Wikströmin saaristokilpailu 17.5. (3)

appears twice in race list

http://hsk-members.appspot.com/races/

**Comment by tvesalainen** [comment]
Tietokannassa Ranking = null.

```
name=LYS 220140517   20140513    20140517    40.0    60.0    LYS 2   <null>  LYS     8   111000  20140516    LYS 0 - 1.14
```

Haku 
SELECT **key** FROM RaceFleet WHERE Ranking != false AND **ancestor** is Root(1)/Year(2014)

Palauttaa rivin torstaikisan listaan.

Dirty fix: korjaa tietokantaan.

**Comment by tvesalainen** [comment]
Miten saitte LYS:t splitattua?

**Comment by hvesalai** [comment]
En tarkkaan muista. Oltaisiinkohan käytetty tuota "lisää laivue" toimintoa tossa Adminissa.
